---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggrepel)
library(broom)
library(modelr)
library(janitor)
theme_set(theme_light())

```

```{r}
# Learning for loop
mult_by_two <- function (x) {
  x * 2
}

values <- c(2, 4, 6)
n <- length(values)
result <- rep(NA, n)
for (i in 1:n) {
  result[i] <- mult_by_two(values[i])
}
print(result)

result <- map(values, mult_by_two)
result
## The values of each element is correct, but map function returns a list vector although we are expecting a numeric vector. If we want a numeric vector, use map_dbl. 
result <- map_dbl(values, mult_by_two)
result

values2 <- 1:5
## Using ifelse function
ifelse(values2 %% 2 == 0, values2 + values2, values2 * values2)

## Using for loop
n <- length(values2)
results <- rep(NA, n)
for (i in 1:n) {
  if(values2[i] %% 2 == 0) {
    results[i] <- values2[i] + values2[i]
  }
  else{
    results[i] <- values2[i] * values2[i]
  }
} 
results

## Using map function
divide_two <- function(x) {
  if(x %% 2 == 0) {
    x + x
  }
  else{
    x * x
  }
}
map_dbl(values2, divide_two)
```

```{r}
data("polls08", package = "qss")
data("pres08", package = "qss")
glimpse(polls08)

polls08_processed <- polls08 %>% 
  mutate(margin = Obama - McCain, 
         elecdate = ymd("2008-11-4"), 
         margin_date = elecdate - middate)

polls08_predicted <- polls08_processed %>% 
  group_by(state) %>% 
  filter(margin_date == min(margin_date)) %>% 
  summarize(predicted_margin = mean(margin)) 

pres08_processed <- pres08 %>% 
  mutate(actual_margin = Obama - McCain)

pres08_polls08 <- pres08_processed %>% 
  inner_join(polls08_predicted, by = "state") %>% 
  mutate(predicted_error = actual_margin - predicted_margin)

## regressing actual margin on predict margin
model <- lm(actual_margin ~ predicted_margin, data = pres08_polls08)
summary(model)

pres08_polls08 %>% 
  ggplot(aes(predicted_error, stat(density))) + 
  geom_histogram(binwidth = 1) 

pres08_polls08 %>% 
  ggplot(aes(predicted_margin, actual_margin)) + 
  geom_point() +
  xlim(-30, 75) +
  geom_text_repel(aes(label = pres08_polls08$state)) +
  geom_hline(yintercept = 0, color = "gray", size = 1) +
  geom_vline(xintercept = 0, color = "gray", size = 1) + 
  labs(x = "Poll results", 
       y = "Actual election results")

```

```{r}
data("pollsUS08", package = "qss")

pollsUS08_processed <- pollsUS08 %>% 
  mutate(elecdate = ymd("2008-11-04"), 
         date_margin = elecdate - middate) 

# empty vectors to store predictions 
obama_pred <- mccain_pred <- rep(NA, 90)
for (i in 1:90) {
  ## take all polls conducted within the past 7 days
  week_data <- subset(pollsUS08_processed, subset = ((date_margin <= (90 - i + 7)) & (date_margin > (90 - i))))
  obama_pred[i] <- mean(week_data$Obama)
  mccain_pred[i] <- mean(week_data$McCain)
}

tibble(weeks = seq(1, 90, 1), 
       obama_pred, 
       mccain_pred) %>% 
  rename("Obama" = obama_pred,  
         "McCain" = mccain_pred) %>% 
  gather(candidate, value, Obama, McCain) %>% 
  mutate(candidate = fct_reorder2(candidate, weeks, value)) %>% 
  ggplot(aes(weeks, value, color = candidate)) +
  geom_point(alpha = 0.5, size = 4) +
  geom_point(data = tibble(weeks = 91, 
                           candidate = c("Obama", "McCain"),
                           value = c(52.93, 45.65)), 
             aes(weeks, value), size = 4, color = "black") +
  geom_vline(xintercept = 91, lty = "dashed") +
  scale_x_continuous(limits = c(0, 91), 
                     breaks = seq(0, 90, 20), 
                     labels = seq(90, 0, -20)) +
  ylim(40, 55) +
  theme(legend.position = "bottom", 
        legend.title = element_blank()) + 
  labs(x = "Days to the election", 
       y = "Supports for candidates (percentage points)")
  
```
## different appoach
```{r}
pollsUS08

elecdate <- ymd("2008-11-4")
all_dates <- seq(min(pollsUS08$middate), elecdate, by = "days")

poll_mean <- function (date, .data, days = 7) {
  filter(.data, 
         as.integer(middate - date) <= 0, 
         as.integer(middate - date) > - !!days) %>% 
  summarize(Obama = mean(Obama), 
            McCain = mean(McCain)) %>% 
  mutate(date = !!date)
}

map_df(all_dates, poll_mean, pollsUS08) %>% 
  gather(candidate, value, -date) %>% 
  ggplot(aes(date, value, color = fct_reorder2(candidate, date, value))) +
  geom_point() +
  geom_line()
## Note that the other arguments for poll_mean are placed after the name of the function as additional arguments to map_df
```

```{r}
data("face", package = "qss")

face_processed <- face %>% clean_names() %>% 
  mutate(d_share = d_votes / (d_votes + r_votes), 
         r_share = r_votes / (d_votes + r_votes), 
         win_margin = d_share - r_share)

face_processed %>% 
  ggplot(aes(d_comp, win_margin, color = w_party)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_manual("Winning\nparty", 
                     values = c(D = "blue", 
                                R = "red"))
```
```{r}
cor(face_processed$d_comp, face_processed$win_margin)
```

```{r}
fit <- lm(win_margin ~ d_comp, data = face_processed)

summary(fit)
```
```{r}
data("pres12", package = "qss")

pres_all <- pres12 %>% 
  mutate(margin = Obama - Romney) %>% 
  left_join(pres08, by = "state", suffix = c("_12", "_08")) %>% 
  clean_names() 

pres_all <- pres_all %>% 
  mutate(obama_08_z = as.numeric(scale(obama_08)), 
         obama_12_z = as.numeric(scale(obama_12)))

## Check if the regression-to-mean phenomenon exists in the presidential election results in 2008 and 2012

pres_all %>% 
  filter(obama_08_z <= quantile(obama_08_z, 0.25)) %>% 
  summarize(margin = mean(obama_12_z > obama_08_z))

pres_all %>% 
  filter(obama_08_z > quantile(obama_08_z, 0.75)) %>% 
  summarize(margin = mean(obama_12_z > obama_08_z))
  
```

```{r}
library(broom)
data("florida", package = "qss")

fit2 <- lm(Buchanan00 ~ Perot96, data = florida)
fit2
glance(fit2) %>% 
  pull(r.squared)

TSS2 <- sum((florida$Buchanan00 - mean(florida$Buchanan00))^2)
SSR2 <- sum(resid(fit2)^2)

R2 <- function (fit) {
  resid <- resid(fit)
  y <- fitted(fit) + resid
  TSS <- sum((y - mean(y))^2)
  SSR <- sum(resid^2)
  R2 <- (TSS - SSR) / TSS
  return(R2)
}

R2(fit2)

# creating a residual plot
augment(fit2) %>% 
  ggplot(aes(.fitted, .resid)) + 
  geom_point()

florida %>% 
  filter(Perot96 == 30739)

# re-compute R2 without the Palm Beach outlier
florida_without_palmbeach <- florida %>% filter(county != "PalmBeach")

fit3 <- lm(Buchanan00 ~ Perot96, data = florida_without_palmbeach)
glance(fit3)
tidy(fit3)

## cheking the improvement of regression lines
florida %>% ggplot(aes(Perot96, Buchanan00)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_abline(intercept = 45.84193340, slope = 0.02435217, lty = "dashed")

## different approach
library(modelr)
florida_grid <- florida %>% 
  data_grid(Perot96) %>% 
  gather_predictions(fit2, fit3) %>% 
  mutate(model = fct_recode(model, "Regression with Palm Beach" = "fit2", 
                            "Regression without Palm Beach" = "fit3")) 

ggplot(data = florida, aes(Perot96, Buchanan00)) + 
  geom_point() +
  geom_line(data = florida_grid, aes(Perot96, pred, lty = model)) +
  geom_label(data = filter(florida, county == "PalmBeach"), 
             mapping = aes(Perot96, Buchanan00, label = county), 
             vjust = "top", 
             hjust = "left") +
  geom_text(data = tibble(label = unique(florida_grid$model), 
                          x = c(20000, 30000), 
                          y = c(1200, 450)), 
            mapping = aes(x = x, y = y, label = label)) +
  theme(legend.position = "none")
  
```

```{r}
data("women", package = "qss")

## checking if the reserved seat is actually occupied by female politicians
women %>% filter(reserved == 1) %>% 
  summarize(prop_female = mean(female))

women %>% filter(reserved == 0) %>% 
  summarize(prop_female = mean(female))
```

```{r}
data("social", package = "qss")
social_releveled <- social %>% mutate(messages = fct_relevel(messages, "Control"))
fit4 <- lm(primary2006 ~ messages, data = social_releveled)
summary(fit4)

social_processed <- social %>% 
  mutate(Control = as.integer(messages == "Control"), 
         Hawthorne = as.integer(messages == "Hawthorne"), 
         Neighbors = as.integer(messages == "Neighbors"))

for (i in unique(social$messages)) {
  social[[i]] <- as.integer(social[["messages"]] == i)
}

## calculate average treatment effect (ate)
ate <- social_releveled %>% 
  group_by(primary2004, messages) %>% 
  summarize(prop_2006 = mean(primary2006)) %>% 
  spread(messages, prop_2006) %>% 
  mutate(ate_Neighbors = Neighbors - Control) 

diff(ate$ate_Neighbors)

```

```{r}
social_neighbor <- social_raw %>% 
  filter((messages == "Control") |
         (messages == "Neighbors")) 

fit5 <- lm(primary2006 ~ primary2004 * messages, data = social_neighbor)
fit5

social_neighbor <- social_neighbor %>% mutate(age = 2006 - yearofbirth)

fit6 <- lm(primary2006 ~ age * messages, data = social_neighbor)
fit6
ate.age <- crossing(age = seq(25, 85, 20), 
         messages = c("Neighbors", "Control")) %>% 
  add_predictions(fit6) %>% 
  spread(messages, pred) %>% 
  mutate(diff = Neighbors - Control)

fit7 <- lm(primary2006 ~ age + I(age^2) + messages + age:messages + I(age^2):messages, data = social_neighbor)
fit7

social_neighbor_processed <- social_raw %>% 
  filter((messages == "Control") |
         (messages == "Neighbors")) %>% 
  mutate(age = 2006 - yearofbirth)

y.hat <- social_neighbor_processed %>% 
  data_grid(age, messages) %>% 
  filter(messages == "Control" | messages == "Neighbors") %>%
  add_predictions(fit7) 

y.hat %>% 
  ggplot(aes(age, pred, color = messages)) +
  geom_line() +
  labs(y = "Predicted turnout rates") +
  theme(legend.position = "bottom", 
        legend.title = element_blank())

## Calculating average treatment effect
y.hat %>% spread(messages, pred) %>% 
  mutate(pred_ate = Neighbors - Control) %>% 
  filter(age > 20, age < 90) %>% 
  ggplot(aes(age, pred_ate)) + 
  geom_line() +
  ylim(0, .1) +
  labs(x = "Age", 
       y = "Estimated average treatment effect") 
```

## Regression Discontinuity (RD) Design
```{r}
data("MPs", package = "qss")
mps <- MPs %>% clean_names()

mps_labour <- mps %>% filter(party == "labour")
mps_tory <- mps %>% filter(party == "tory")

labour_fit1 <- lm(data = filter(mps_labour, margin < 0), ln_net ~ margin)
labour_fit2 <- lm(data = filter(mps_labour, margin > 0), ln_net ~ margin)

tory_fit1 <- lm(data = filter(mps_tory, margin < 0), ln_net ~ margin)
tory_fit2 <- lm(data = filter(mps_tory, margin > 0), ln_net ~ margin)

```

```{r}
## plot separate regression lines for the Labour party
mps_labour %>% 
  ggplot(aes(margin, ln_net)) + 
  geom_point(aes(alpha = .8)) +
  geom_line(data = augment(labour_fit1), aes(margin, .fitted), color = "red") + 
  geom_line(data = augment(labour_fit2), aes(margin, .fitted), color = "red") 

mps_tory %>% 
  ggplot(aes(margin, ln_net)) + 
  geom_point(aes(alpha = .8)) +
  geom_line(data = augment(tory_fit1), aes(margin, .fitted), color = "red") + 
  geom_line(data = augment(tory_fit2), aes(margin, .fitted), color = "red") 
```

```{r}
ggplot(mutate(mps, winner = (margin > 0)),
       aes(x = margin, y = ln_net)) +
  geom_ref_line(v = 0, size = 2, colour = "gray") +
  geom_point(alpha = 0.5, size = 2.5) +
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = winner)) +
  facet_wrap(~ party) +
  labs(x = "margin of victory", y = "log net wealth at death")
```

```{r}
tory_fit1 <- lm(data = filter(mps_tory, margin < 0), ln_net ~ margin)
tory_fit2 <- lm(data = filter(mps_tory, margin > 0), ln_net ~ margin)

tory_nonMP <- exp(predict(tory_fit1, newdata = tibble(margin = 0)))
tory_MP <- exp(predict(tory_fit2, newdata = tibble(margin = 0)))

# calculating estimated causal effect of beng MP in terms of net wealth (pounds)
tory_MP - tory_nonMP

```

```{r}
data(list = c("intrade08", "intrade12"), package = "qss")

intrade08_processed <- intrade08 %>% 
  filter(day == "2008-11-03") %>% 
  mutate(predicted_winner = ifelse(PriceD > PriceR, "Obama", "McCain")) 

pres08_processed <- pres08 %>% 
  mutate(actual_winner = ifelse(Obama > McCain, "Obama", "McCain")) %>% 
  select(state.name, state, actual_winner)

intrade08_processed %>% 
  left_join(pres08_processed, by = "state") %>% 
  mutate(classified = ifelse(predicted_winner == actual_winner, "classified", "misclassified")) %>% 
  filter(classified == "misclassified") %>% 
  pull(statename)

myfunction <- function (date, .data, days = 1) {
  filter(day == date - as.Date(days)) %>% 
  mutate(predicted_winner = ifelse(PriceD > PriceR, "Obama", "McCain"))
}

myfunction("2008-11-04", intrade08)

```
Question 4.5.2
```{r}
# question 4-5-2-1
data("progresa", package = "qss")

progresa_select <- progresa %>% 
  select(treatment, t2000, pri2000s) 

progresa_processed <- progresa_select %>% 
  group_by(treatment) %>% 
  summarize(avg_turnout = mean(t2000), 
            avg_support = mean(pri2000s)) 

# difference in means
mean1 <- progresa_processed$avg_turnout[2] - progresa_processed$avg_turnout[1] 
mean2 <- progresa_processed$avg_support[2] - progresa_processed$avg_support[1]
mean1 - mean2
# 0.6471805

fit_turnout1 <- lm(t2000 ~ treatment, data = progresa_select)
fit_support1 <- lm(pri2000s ~ treatment, data = progresa_select)
summary(fit_turnout)
coef(fit_turnout) - coef(fit_support)
# 0.6471805
```

```{r}
# question 4-5-2-2
fit_turnout2 <- lm(t2000 ~ treatment + avgpoverty + pobtot1994 + votos1994 + pri1994 + pan1994 + prd1994, data = progresa)
fit_turnout2
summary(fit_turnout2)

fit_support2 <- lm(pri2000s ~ treatment + avgpoverty + pobtot1994 + votos1994 + pri1994 + pan1994 + prd1994, data = progresa)
fit_support2
summary(fit_support2)

# question 4-5-2-3
fit_turnout3 <- lm(t2000 ~ treatment + avgpoverty + I(log(pobtot1994)) + pri1994s + pan1994s + prd1994s, data = progresa)
fit_turnout3
summary(fit_turnout3)

fit_support3 <- lm(pri2000s ~ treatment + avgpoverty + I(log(pobtot1994)) + pri1994s + pan1994s + prd1994s, data = progresa)
fit_support3
summary(fit_support3)
```

```{r}
# question 4-5-2-4
progresa %>% 
  ggplot(aes(treatment, pobtot1994)) + 
  geom_boxplot(aes(group = treatment))

progresa %>% 
  select(treatment, pobtot1994, avgpoverty, t1994, pri1994s) %>% 
  gather(variables, value, -treatment) %>% 
  ggplot(aes(treatment, value, group = treatment)) + 
  geom_boxplot() +
  facet_wrap(~ variables, scales = "free_y")
```
```{r}
# question 4-5-2-6
progresa
fit_turnout4 <- lm(t2000 ~ treatment + I(log(pobtot1994)) + avgpoverty + I(avgpoverty^2) + treatment:avgpoverty + treatment:I(avgpoverty^2), data = progresa)
fit_turnout4
summary(fit_turnout4)

fit_support4 <- lm(pri2000s ~ treatment + I(log(pobtot1994)) + avgpoverty + I(avgpoverty^2) + treatment:avgpoverty + treatment:I(avgpoverty^2), data = progresa)
fit_support4
summary(fit_support4)

# Estimate the average effects for unique observed values and plot them as a function of the average poverty level. 
progresa %>% 
  distinct(treatment, pobtot1994, avgpoverty) %>% 
  add_predictions(fit_turnout4) %>% 
  ggplot(aes(avgpoverty, pred)) +
  geom_line() + 
  facet_wrap(~ treatment)

progresa %>% count(avgpoverty)
```

```{r}
# question 4.5.3
data("transfer", package = "qss")
transfer <- transfer %>% clean_names()
## 10188, 13584, 16980; create a single variable that characterizes the difference from the closest population cutoff
transfer_processed <- transfer %>% mutate(diff = case_when(pop82 < 10188 ~ (pop82 - 10188) / 10188, 
                                     pop82 >= 10188 & pop82 < 11886 ~ (pop82 - 10188) / 10188, 
                                     pop82 >= 11886 & pop82 < 13584 ~ (pop82 - 13584) / 13584,
                                     pop82 >= 13584 & pop82 < 15282 ~ (pop82 - 13584) / 13584, 
                                     pop82 >= 15282 & pop82 < 16980 ~ (pop82 - 16980) / 16980,
                                     pop82 > 16980 ~ (pop82 - 16980) / 16980)) %>% 
  mutate(diff = 100 * diff) %>% 
  filter(diff > -3, diff < 3) 

transfer_processed %>% 
  gather(indicator, value, educ91, poverty91, literate91) %>% 
  select(diff, indicator, value) %>% 
  mutate(indicator = fct_recode(indicator,
                                "Literacy" = "literate91", 
                                "Years of education" = "educ91",
                                "Poverty rate" = "poverty91")) %>% 
  mutate(receiver = diff > 0) %>% 
  ggplot(aes(diff, value)) +
  geom_ref_line(v = 0, size = 2, colour = "gray") +
  geom_point(alpha = 0.5, size = 2.5) +
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = receiver)) + 
  facet_wrap(~ indicator, scales = "free_y") + 
  labs(x = "Difference from population thresholds for government transfer (percentage point)", 
       y = "Degree of social welfare")

```

```{r}
educ_fit1 <- lm(data = filter(transfer_processed, diff < 0), educ91 ~ diff)
educ_fit2 <- lm(data = filter(transfer_processed, diff > 0), educ91 ~ diff)

poverty_fit1 <- lm(data = filter(transfer_processed, diff < 0), poverty91 ~ diff)
poverty_fit2 <- lm(data = filter(transfer_processed, diff > 0), poverty91 ~ diff)

literate_fit1 <- lm(data = filter(transfer_processed, diff < 0), literate91 ~ diff)
literate_fit2 <- lm(data = filter(transfer_processed, diff > 0), literate91 ~ diff)

predict(net_edu_fit2, newdata = tibble(diff = 0)) - predict(net_edu_fit1, newdata = tibble(diff = 0))

## Create a function for calculation
predict_function <- function (model1, model2) {
  spread_predictions(data = tibble(diff = 0), 
                   model1, model2) %>% 
  mutate(ate = model2 - model1) %>% 
  pull(ate)
}

## Calculating average treatment effect for each indicator
predict_function(educ_fit1, educ_fit2)
predict_function(poverty_fit1, poverty_fit2)
predict_function(literate_fit1, literate_fit2)
```

