---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggrepel)
library(maps)
theme_set(theme_light())
options(scipen = 999)
```

```{r}
data("us.cities", package = "maps")
glimpse(us.cities)
```

```{r}
usa_map <- map_data("usa")
data("usa", package = "maps")
capitals <- us.cities %>% filter(capital == 2, 
                                 !country.etc %in% c("HI", "AK"))

ggplot() + 
  geom_map(map = usa_map) +
  borders(database = "usa") +
  geom_point(data = capitals, aes(long, lat, size = pop)) + 
  scale_size_area() +
  coord_quickmap() +
  labs(title = "US State Capital")
```

```{r}
ca_cities <- filter(us.cities, country.etc == "CA") %>% 
  arrange(desc(pop)) %>% 
  slice(1:7) %>% 
  mutate(name = str_replace_all(name, "CA", ""))

ggplot() + 
  geom_map(map = usa_map) +
  borders(database = "state", regions = "California") + 
  geom_point(data = ca_cities, aes(long, lat)) + 
  geom_text_repel(data = ca_cities, aes(long, lat, label = name)) + 
  coord_quickmap()
```

# Colors in R
```{r}
allcolors <- colors()
head(allcolors)
length(allcolors)

red <- rgb(red = 1, green = 0, blue = 0)
green <- rgb(red = 0, green = 1, blue = 0)
blue <- rgb(red = 0, green = 0, blue = 1)

black <- rgb(red = 0, green = 0, blue = 0)
white <- rgb(red = 1, green = 1, blue = 1)
```

```{r}
ggplot(data = tibble(x = rep(1:4, each = 2), 
       y = x + rep(c(0, 0.2), times = 2), 
       color = rep(c("black", "red"), each = 4), 
       alpha = c(1, 1, .5, .5, 1, 1, .5, .5)),
       aes(x, y, color = color, alpha = alpha)) +
  geom_point(size = 15) + 
  scale_color_identity() + 
  scale_alpha_identity() +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
data("pres08", package = "qss")
df <- pres08 %>% 
  mutate(state_color = if_else(Obama > McCain, "blue", "red")) %>% 
  mutate(dem = Obama / (Obama + McCain), 
         rep = McCain / (Obama + McCain))

ggplot() + 
  geom_map(map = usa_map) +
  borders(database = "state", regions = "California", fill = "blue") +
  coord_quickmap() +
  theme_void()
  
cal_color <- filter(df, state == "CA") %>% {
    rgb(red = .$rep, green = 0, blue = .$dem)
}

ggplot() +
  borders(database = "state", regions = "California", fill = cal_color) +
  coord_quickmap() +
  theme_void()
```

```{r}
map(database = "state") 
for (i  in 1:nrow(df)) {
    if ( (df$state[i] != "HI") & (df$state[i] != "AK") &
        (df$state[i] != "DC")) {
        maps::map(database = "state", 
            regions = df$state.name[i],
            col = ifelse(df$rep[i] > df$dem[i], "red", "blue"),
            fill = TRUE, 
            add = TRUE)
    }
}
```

```{r}
map(database = "state") 
for (i  in 1:nrow(df)) {
    if ( (df$state[i] != "HI") & (df$state[i] != "AK") &
        (df$state[i] != "DC")) {
        ggplot + borders(database = "state", 
                                    regions = df$state.name[i], 
                                    fill =  ifelse(df$rep[i] > df$dem[i], "red", "blue")) + 
        coord_quickmap() + 
        theme_void()
    }
}
```

```{r}
pres08_states <- map_data("state") %>% 
  left_join(mutate(df, state.name = str_to_lower(state.name)), by = c("region" = "state.name")) %>% 
  filter(!is.na(state_color)) %>% 
  mutate(party = ifelse(dem > rep, "dem", "rep"), 
         color = map2_chr(dem, rep, ~ rgb(blue = .x, red = .y, green = 0)))

ggplot(pres08_states) +
  geom_polygon(aes(long, lat, group = group, fill = party)) +
  coord_quickmap() +
  scale_fill_manual(values = c("dem" = "blue", "rep" = "red")) +
  theme_void()

ggplot(pres08_states) +
  geom_polygon(aes(long, lat, group = group, fill = color)) +
  coord_quickmap() +
  scale_fill_identity() +
  theme_void()

# A different, more clearly distinghishable approach
ggplot(pres08_states) +
  geom_polygon(aes(long, lat, group = group, fill = dem)) +
  coord_quickmap() +
  scale_fill_gradient2(low = "red", high = "blue", midpoint = .5) +
  theme_void()
```
## Expansion of Walmart
```{r}
data("walmart", package = "qss")

# We don't need to worry about colors since ggplot will handles that; 
ggplot() + 
  borders(database = "state") +
  geom_point(data = mutate(walmart, size = ifelse(type == "DistributionCenter", 2.5, 1)), 
             aes(long, lat, color = type, size = size), 
             alpha = .5) + 
  coord_quickmap() +
  scale_size_identity() +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  labs(title = "National Distribution of Walmart") +
  theme_void()
```

```{r}
walmart.map <- function (data, year) {
  walmart_map <- walmart %>% filter(opendate < make_date(year, 1, 1))
  ggplot() + 
    borders(database = "state") +
    geom_point(data = mutate(walmart_map, size = ifelse(type == "DistributionCenter", 2.5, 1)), 
             aes(long, lat, color = type, size = size), 
             alpha = .5) + 
  coord_quickmap() +
  scale_size_identity() +
  theme_void() +
  labs(color = "", 
       title = year)  
}

years <- c(1975, 1985, 1995, 2005)
walk(years, ~ print(walmart.map(walmart, .x)))

```
## Animate the expansion
```{r}
library(gganimate)

ggplot() +
    borders(database = "state") +
    geom_point(aes(x = long, y = lat,
                   colour = type,
                   fill = type),
               data = walmart) +
    coord_quickmap() +
    theme_void() + 
    labs(title = "Year: {frame_time}") +
    transition_time(year(opendate)) 
```

### Exercise 5-5-3 (Mapping US presidential election over time)
```{r}
data("elections", package = "qss")
elections_joined <- map_data("county") %>% left_join(elections, by = c("subregion" = "county"))

# Begin with MA and AR and visualize the county-level outcome by coloring
# counties based on the two-party vote share. Use the county database in the
# maps package. The regions argument of the map function enables us to specify
# the state and county. The argument accepts a character vector, each entry of
# which has the syntax state, county. Provide a brief comment.
elections_filtered <- 
  elections_joined %>% 
  mutate(rep_share = rep / (rep + dem), 
         dem_share = dem / (rep + dem)) %>% 
  filter(year == 2008)

county_2008 <- function (x) {
  ggplot() +
  borders(database = "county", regions = as.character(x)) +
  geom_polygon(aes(long, lat, group = group, fill = dem_share), 
               data = filter(elections_filtered, region == as.character(x))) +
  scale_fill_gradient2(high = "blue", low = "red", midpoint = .5) +
  coord_quickmap() +
  theme_void() +
  ggtitle(str_to_title(as.character(x)))
}

two_states <- c("massachusetts", "arizona")
walk(two_states, ~ print(county_2008(.x)))

# subsetting all the states
states <- unique(elections_filtered$region)
walk(states, ~ print(county_2008_all(.x)))

# plotting the election results at county level
ggplot() +
  borders(database = "county") +
  geom_polygon(aes(long, lat, group = group, fill = dem_share), 
               data = filter(elections_filtered, region %in% states)) +
  scale_fill_gradient2(high = "blue", low = "red", midpoint = .5) +
  coord_quickmap() +
  theme_void() + 
  labs(title = "2008 county-level election results across the United States")
```

```{r}
# In this exercise, we quantify the degree of partisan segregation for each
# state. We consider a state to be politically segregated if Democrats and
# Republicans tend to live in different counties. A common way to quantify the
# degree of residential segregation is to use the dissimilarity index given by.
# Using data on Democratic and Republican votes from the 2008 presidential
# election, calculate the dissimilarity index for each state. Which states are
# among the most (least) segregated according to this measure? Visualize the
# result as a map. Briefly comment on what you observe.

election_processed <- elections_filtered %>% 
  distinct(state, subregion, .keep_all = TRUE) %>% 
  select(state, subregion, everything()) %>% 
  select(-region) %>% 
  group_by(state) %>% 
  mutate(rep_total = sum(rep), 
         dem_total = sum(dem)) %>% 
  ungroup()

election_processed %>% 
  mutate(dis_index = sum(abs((dem / dem_total) - (rep / rep_total))) / 2)
  
dis_index <- function (county) {
  sum(abs(dem / dem_sum - rep / rep_sum)) / 2
}
```

