---
title: "china-map-practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(hchinamap)
theme_set(theme_light())
```

```{r}
dir <- tempdir()
download.file('https://czxb.github.io/br/chinadf.rda', file.path(dir, 'chinadf.rda'))
load(file.path(dir, 'chinadf.rda'), verbose = TRUE)

chinadf
hchinamap(name = chinadf$name, 
          value = chinadf$value, 
          region = "China", 
          width = "100%", 
          height = "400px", 
          theme = "darkunica",
          minColor = "red", 
          maxColor = "blue")
```

# China sf data transformation

```{r}
library(sf)
library(viridis)
library(viridisLite)
library(spData)
library(janitor)
library(readxl)
theme_set(theme_void())

china_provinces <- st_read("~/Desktop/china-map-data/gadm36_CHN_1.shp") %>% clean_names()
object.size(china_provinces)

china_cities <- st_read("~/Desktop/china-map-data/gadm36_CHN_2.shp") %>% clean_names()
china_counties <- st_read("~/Desktop/china-map-data/gadm36_CHN_3.shp") %>% clean_names()

provinces_raw <- st_read("~/Desktop/china-map-data/CHGIS_V4_1997_PROV_PGN.shp") %>% clean_names()

province_data <- read_excel("~/Desktop/province_data.xlsx") %>% mutate(location = fct_recode(location, "Ningxia Hui" = "Ningxia", "Xizang" = "Tibet", "Xinjiang Uygur" = "Xinjiang"))
```

# China provinces: data cleaning

```{r}
provinces_raw
plot(st_geometry(provinces_raw))
ggplot(data = provinces_raw) +
  geom_sf()

provinces %>% st_drop_geometry()
```


```{r}
china_provinces_df <- china_provinces %>% st_drop_geometry() %>% mutate(nl_name_1 = str_replace(nl_name_1, "\\|", "/")) %>% 
  separate(nl_name_1, c("chinese_1", "chinese_2"), sep = "/")

china_provinces_data <- china_provinces_df %>% left_join(province_data, by = c("name_1" = "location"))

china_provinces_data_geometry <- cbind(china_provinces_data, china_provinces$geometry)

# Convert data.frame into sf object
china_provinces_data_sf <- st_sf(china_provinces_data_geometry)
plot(china_provinces_data_sf["gdp_percapita"])

```

## Attribute data operations

```{r}
china_provinces_df %>% View()
```

```{r}
plot(st_geometry(china_provinces))
plot(st_geometry(china_provinces %>% filter(engtype_1 == "Autonomous Region")), col = "blue", add = TRUE)

plot(china_provinces["engtype_1"])
ggplot(data = provinces) + geom_sf()
```

```{r}
shandong <- china_provinces %>% filter(name_1 == "Shandong")
plot(st_geometry(shandong), col = gray, lwd = 3)
ggplot() + geom_sf(data = shandong)

shandong_city <- china_cities %>% filter(name_1 == "Shandong")
ggplot() + geom_sf(data = shandong_city)

beijing_city <- china_counties %>% filter(name_1 == "Beijing")
ggplot() + geom_sf(data = beijing_city)
```

# China cities

```{r}
china_cities

plot(st_geometry(china_cities))
plot(china_cities["type_2"])

anhui <- china_cities %>% filter(name_1 == "Anhui")
glimpse(anhui)
plot(st_geometry(anhui), expandBB = c(2.5, 2, 3.5, 3.5), col = "red", lwd = 3)
plot(st_geometry(china_cities), add = TRUE)
```

```{r}
ggplot(data = anhui, aes(fill = engtype_2)) +
  geom_sf() +
  geom_sf_text(aes(label = name_2)) +
  # 経緯度線を入れない
  coord_sf(datum = NA) +
  guides(fill = F) +
  theme_void() 
```

```{r}
library(tmap)

qtm(anhui)
qtm(china_provinces)
```

# China counties

```{r}
china_counties

plot(st_geometry(china_counties))
```

```{r}

```

