---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)

minwage <- read_csv("minwage.csv")

```

```{r}
minwage %>% 
  mutate(wage_diff = wageAfter - wageBefore, 
         full_diff = fullAfter - fullBefore,
         part_diff = partAfter - partBefore) %>% 
  group_by(location, chain) %>% 
  summarize(avg_wage_diff = mean(wage_diff),
            avg_full_diff = mean(full_diff), 
            avg_part_diff = mean(part_diff)) %>% 
  gather(type, value, -location, -chain) %>% 
  ggplot(aes(location, value, fill = type)) +
  geom_col(position = "dodge") +
  facet_wrap(~ chain) +
  coord_flip()
  
minwage %>% 
  mutate(location = ifelse(location == "PA", location, "NJ")) %>% 
  View()
  group_by(location) %>% 
  summarize(prop_before = mean(wageBefore < 5.05), 
            prop_after = mean(wageAfter < 5.05))

minwage %>% 
  mutate(location = ifelse(location == "PA", location, "NJ")) %>% 
  group_by(location) %>% 
  summarize(pct_full_after = mean(fullAfter / (fullAfter + partAfter))) 

## statistical check for the Burgerking effect
minwage %>% 
  mutate(location = ifelse(location == "PA", location, "NJ")) %>% 
  group_by(location) %>% 
  mutate(before = mean(fullBefore / (fullBefore + partBefore)), 
            after = mean(fullAfter / (fullAfter + partAfter))) %>%
  gather(time, value, before, after) %>% 
  mutate(time = fct_relevel(time, "before", "after")) %>% 
  ggplot(aes(time, value, color = location)) + 
  geom_point() + 
  geom_line(aes(group = location)) + 
  expand_limits(ymin = 0.25, ymax = 0.35) +
  theme_classic()
  

## statistical check for the location effect
minwage %>% 
  filter(location %in% c("northNJ", "southNJ", "PA")) %>% 
  group_by(location) %>% 
  summarize(pct_full_before = mean(fullBefore / (fullBefore + partBefore)), 
            pct_full_after = mean(fullAfter / (fullAfter + partAfter)))
```

