---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
## calling for libraries
library(tidyverse)
library(kableExtra)

star <- read_csv("STAR.csv")

```

```{r message=FALSE, echo=FALSE}
tidied_star <- star %>% 
  mutate(kinder = recode(classtype, `1` = "small", `2` = "regular", `3` = "regular_aid"), 
         race = recode(race, `1` = "white", `2` = "black", `4` = "hispanic", .default = "others")) %>% 
  filter(!is.na(race)) 

## comparing average scores of reading and math tests between small and regular classes

tidied_star %>% 
  group_by(kinder) %>% 
  summarize(avg_math = mean(g4math, na.rm = T), 
            avg_reading = mean(g4reading, na.rm = T))

## compare the standard deviations of the test scores

tidied_star %>% 
  group_by(kinder) %>% 
  summarize(sd_math = sd(g4math, na.rm = T), 
            sd_reading = sd(g4reading, na.rm = T))

## compare the entire range of test scores; a high score and low score

tidied_star %>% 
  group_by(kinder) %>% 
  summarize_at(vars(g4math, g4reading), quantile, 0.66, na.rm = TRUE)

tidied_star %>% 
  count(small = sum(yearssmall == 4), 
        small_regular = sum(yearssmall == 1 & kinder %in% c("regular", "regular_aid")))

tidied_star %>% 
  group_by(yearssmall) %>% 
  summarize(avg_math = mean(g4math, na.rm = T), 
            median_math = median(g4math, na.rm = T), 
            avg_reading = mean(g4reading, na.rm = T), 
            median_reading = median(g4reading, na.rm = T)) %>% 
  kable() %>% 
  kable_styling()
        
  
tidied_star %>% 
  mutate(race = ifelse(race == "white", race, "minority")) %>% 
  group_by(race, kinder) %>% 
  summarize(avg_math = mean(g4math, na.rm = TRUE),
            avg_reading = mean(g4reading, na.rm = TRUE))

tidied_star %>% 
  group_by(kinder) %>% 
  summarize(avg_hs = mean(hsgrad == 1, na.rm = T))

```

